# test config mushra page, waveform, 11 conditions, no looping


testname: CI MUSHRA
testId: ci_mushra
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php

pages:
    - type: mushra
       id: MUSHRA
       name: CIMUSHRA
       content: This is a MUSHRA page.
       showWaveform: true
       enableLooping: false 
       reference: configs/Niyazi/1/1_reference.wav
       randomize : true
       createAnchor35: false
       createAnchor70: false
       stimuli:
           C1: configs/Niyazi/1/1_200HP.wav
           C2: configs/Niyazi/1/1_400HP.wav
           C3: configs/Niyazi/1/1_600HP.wav
           C4: configs/Niyazi/1/1_800HP.wav
           C5: configs/Niyazi/1/1_1000HP.wav
           C6: configs/Niyazi/1/1_1000_1200BP.wav
        
    - type: finish
       name: Thank you
       content: Thank you for attending!
       popupContent: Your results were sent. Goodbye and have a nice day   
       showResults: true
       writeResults: true


