# MUSHRA ORIGINAL

testname: MUSHRA_Original 
testId: result_original
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php

pages:

    - type: generic
      id: mushra_instructions
      name: PLEASE READ THE INSTRUCTION CAREFULLY!
      content: <p>The purpose of the test is to invite you to assign your grades using the quality scale. Your grades should reflect your subjective judgment of the quality level for each of the sound excerpts presented to you. Each trial will contain 7 signals to be graded. Each of the items is approximately 5 s long. You should listen to the reference and all the test conditions by clicking on the respective buttons. You may listen to the signals in any order, any number of times.In evaluating the sound excerpts, please note that you should not necessarily give a grade in the “bad” category to the sound excerpt with the lowest quality in the test. However one or more excerpts must be given a grade of 100 because the unprocessed reference signal is included as one of the excerpts to be graded.</p>
    - type: consent
      id: consent_page
      name: Consent
      mustConsent: true
      content: <p>You are participating in a listening test. For this, we want to store the answers you give to the following questions.<br>Do you give consent for this?</p>
    - type: mushra
      id: trial1
      name: mushra
      content: This training shows how to use our user interface. Please perform the underlined instructions to proceed with the training session. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
    -
        - random   
        - type: mushra
          id: sound1
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/1/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/1/-3dB.wav
               C2: configs/Niyazi/Normal/1/-6dB.wav
               C3: configs/Niyazi/Normal/1/-9dB.wav
               C4: configs/Niyazi/Normal/1/-12dB.wav
               C5: configs/Niyazi/Normal/1/vdb.wav
               C6: configs/Niyazi/Normal/1/anchor.wav
      -   
        - type: mushra
          id: sound2
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/2/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/2/-3dB.wav
               C2: configs/Niyazi/Normal/2/-6dB.wav
               C3: configs/Niyazi/Normal/2/-9dB.wav
               C4: configs/Niyazi/Normal/2/-12dB.wav
               C5: configs/Niyazi/Normal/2/vdb.wav
               C6: configs/Niyazi/Normal/2/anchor.wav
      -    
        - type: mushra
          id: sound3
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/3/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/3/-3dB.wav
               C2: configs/Niyazi/Normal/3/-6dB.wav
               C3: configs/Niyazi/Normal/3/-9dB.wav
               C4: configs/Niyazi/Normal/3/-12dB.wav
               C5: configs/Niyazi/Normal/3/vdb.wav
               C6: configs/Niyazi/Normal/3/anchor.wav
      -  
        - type: mushra
          id: sound4
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/4/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/4/-3dB.wav
               C2: configs/Niyazi/Normal/4/-6dB.wav
               C3: configs/Niyazi/Normal/4/-9dB.wav
               C4: configs/Niyazi/Normal/4/-12dB.wav
               C5: configs/Niyazi/Normal/4/vdb.wav
               C6: configs/Niyazi/Normal/4/anchor.wav
      -         
        - type: mushra
          id: sound5
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/5/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/5/-3dB.wav
               C2: configs/Niyazi/Normal/5/-6dB.wav
               C3: configs/Niyazi/Normal/5/-9dB.wav
               C4: configs/Niyazi/Normal/5/-12dB.wav
               C5: configs/Niyazi/Normal/5/vdb.wav
               C6: configs/Niyazi/Normal/5/anchor.wav
      -  
        - type: mushra
          id: sound6
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/6/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/6/-3dB.wav
               C2: configs/Niyazi/Normal/6/-6dB.wav
               C3: configs/Niyazi/Normal/6/-9dB.wav
               C4: configs/Niyazi/Normal/6/-12dB.wav
               C5: configs/Niyazi/Normal/6/vdb.wav
               C6: configs/Niyazi/Normal/6/anchor.wav
      -  
        - type: mushra
          id: sound7
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/7/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/7/-3dB.wav
               C2: configs/Niyazi/Normal/7/-6dB.wav
               C3: configs/Niyazi/Normal/7/-9dB.wav
               C4: configs/Niyazi/Normal/7/-12dB.wav
               C5: configs/Niyazi/Normal/7/vdb.wav
               C6: configs/Niyazi/Normal/7/anchor.wav
      -  
        - type: mushra
          id: sound8
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/8/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/8/-3dB.wav
               C2: configs/Niyazi/Normal/8/-6dB.wav
               C3: configs/Niyazi/Normal/8/-9dB.wav
               C4: configs/Niyazi/Normal/8/-12dB.wav
               C5: configs/Niyazi/Normal/8/vdb.wav
               C6: configs/Niyazi/Normal/8/anchor.wav
      -
        - type: mushra
          id: sound9
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/9/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/9/-3dB.wav
               C2: configs/Niyazi/Normal/9/-6dB.wav
               C3: configs/Niyazi/Normal/9/-9dB.wav
               C4: configs/Niyazi/Normal/9/-12dB.wav
               C5: configs/Niyazi/Normal/9/vdb.wav
               C6: configs/Niyazi/Normal/9/anchor.wav
      -   
        - type: mushra
          id: sound10
          name: MUSHRA TEST - ORIGINAL -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/Normal/10/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/Normal/10/-3dB.wav
               C2: configs/Niyazi/Normal/10/-6dB.wav
               C3: configs/Niyazi/Normal/10/-9dB.wav
               C4: configs/Niyazi/Normal/10/-12dB.wav
               C5: configs/Niyazi/Normal/10/vdb.wav
               C6: configs/Niyazi/Normal/10/anchor.wav
             
    - type: finish
      name: Thank you
      content: Thank you for attending
      popupContent: Your results were sent. Goodbye and have a nice day
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: ParticipantCode
            name: ParticipantCode      
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
