# MUSHRA CI SIMULATION


testname: MUSHRA_Simulation
testId: SHS598_Simulation
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: generic
      id: mushra_instructions
      name: PLEASE READ THE INSTRUCTION CAREFULLY!
      content: The purpose of the test is to invite you to assign your grades using the quality scale. Your grades should reflect your subjective judgement of the quality level for each of the sound excerpts presented to you. Each trial will contain 7 signals to be graded. Each of the items is approximately 5 s long. You should listen to the reference and all the test conditions by clicking on the respective buttons. You may listen to the signals in any order, any number of times.In evaluating the sound excerpts, please note that you should not necessarily give a grade in the “bad” category to the sound excerpt with the lowest quality in the test. However one or more excerpts must be given a grade of 100 because the unprocessed reference signal is included as one of the excerpts to be graded.
    - 
      - random   
      -   
        - type: mushra
          id: sound1
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/1/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/1/-3dB.wav
               C2: configs/Niyazi/CI/1/-6dB.wav
               C3: configs/Niyazi/CI/1/-9dB.wav
               C4: configs/Niyazi/CI/1/-12dB.wav
               C5: configs/Niyazi/CI/1/vdb.wav
               C6: configs/Niyazi/CI/1/anchor.wav
      -   
        - type: mushra
          id: sound2
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/2/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/2/-3dB.wav
               C2: configs/Niyazi/CI/2/-6dB.wav
               C3: configs/Niyazi/CI/2/-9dB.wav
               C4: configs/Niyazi/CI/2/-12dB.wav
               C5: configs/Niyazi/CI/2/vdb.wav
               C6: configs/Niyazi/CI/2/anchor.wav
      -    
        - type: mushra
          id: sound3
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/3/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/3/-3dB.wav
               C2: configs/Niyazi/CI/3/-6dB.wav
               C3: configs/Niyazi/CI/3/-9dB.wav
               C4: configs/Niyazi/CI/3/-12dB.wav
               C5: configs/Niyazi/CI/3/vdb.wav
               C6: configs/Niyazi/CI/3/anchor.wav
      -  
        - type: mushra
          id: sound4
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/4/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/4/-3dB.wav
               C2: configs/Niyazi/CI/4/-6dB.wav
               C3: configs/Niyazi/CI/4/-9dB.wav
               C4: configs/Niyazi/CI/4/-12dB.wav
               C5: configs/Niyazi/CI/4/vdb.wav
               C6: configs/Niyazi/CI/4/anchor.wav
      -         
        - type: mushra
          id: sound5
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/5/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/5/-3dB.wav
               C2: configs/Niyazi/CI/5/-6dB.wav
               C3: configs/Niyazi/CI/5/-9dB.wav
               C4: configs/Niyazi/CI/5/-12dB.wav
               C5: configs/Niyazi/CI/5/vdb.wav
               C6: configs/Niyazi/CI/5/anchor.wav
      -  
        - type: mushra
          id: sound6
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/6/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/6/-3dB.wav
               C2: configs/Niyazi/CI/6/-6dB.wav
               C3: configs/Niyazi/CI/6/-9dB.wav
               C4: configs/Niyazi/CI/6/-12dB.wav
               C5: configs/Niyazi/CI/6/vdb.wav
               C6: configs/Niyazi/CI/6/anchor.wav
      -  
        - type: mushra
          id: sound7
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/7/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/7/-3dB.wav
               C2: configs/Niyazi/CI/7/-6dB.wav
               C3: configs/Niyazi/CI/7/-9dB.wav
               C4: configs/Niyazi/CI/7/-12dB.wav
               C5: configs/Niyazi/CI/7/vdb.wav
               C6: configs/Niyazi/CI/7/anchor.wav
      -  
        - type: mushra
          id: sound8
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/8/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/8/-3dB.wav
               C2: configs/Niyazi/CI/8/-6dB.wav
               C3: configs/Niyazi/CI/8/-9dB.wav
               C4: configs/Niyazi/CI/8/-12dB.wav
               C5: configs/Niyazi/CI/8/vdb.wav
               C6: configs/Niyazi/CI/8/anchor.wav
      -
        - type: mushra
          id: sound9
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/9/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/9/-3dB.wav
               C2: configs/Niyazi/CI/9/-6dB.wav
               C3: configs/Niyazi/CI/9/-9dB.wav
               C4: configs/Niyazi/CI/9/-12dB.wav
               C5: configs/Niyazi/CI/9/vdb.wav
               C6: configs/Niyazi/CI/9/anchor.wav
      -   
        - type: mushra
          id: sound10
          name: MUSHRA TEST - CI SIMULATION -
          content: Please give a grade to each signal. 
          showWaveform: true
          enableLooping: false 
          reference: configs/Niyazi/CI/10/standard.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
               C1: configs/Niyazi/CI/10/-3dB.wav
               C2: configs/Niyazi/CI/10/-6dB.wav
               C3: configs/Niyazi/CI/10/-9dB.wav
               C4: configs/Niyazi/CI/10/-12dB.wav
               C5: configs/Niyazi/CI/10/vdb.wav
               C6: configs/Niyazi/CI/10/anchor.wav
             
    - type: finish
      name: Thank you
      content: Thank you for attending
      popupContent: Your results were sent. Goodbye and have a nice day
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: ParticipantCode
            name: ParticipantCode            
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
